server:
  port: 8000

#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  type-aliases-package: com.demo.api.po
#  mapper-locations:
#    - classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: demo-cloud-server-provider
  aop:
    auto: true

eureka:
  client:
    service-url:
      defaultZone: http://ek-server:7001/eureka/
  instance:
    instance-id: dept-server
    appname: dept-provider
    prefer-ip-address: true



management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

info:
  appname: djsl
  version: $project.version$

